import { db } from './firebase';
import { doc, setDoc, getDoc, collection, query, where, orderBy, limit, getDocs } from 'firebase/firestore';
import type { Board } from '../engine/gameLogic';
import { generatePuzzle } from '../engine/puzzleGenerator';

const USE_LOCAL = import.meta.env.VITE_USE_LOCAL_EMULATOR === 'true';

export interface PuzzleData {
  regions: number[][];
  solution?: { rowIndex: number; columnIndex: number }[];
}

export interface ProgressData {
  grid: Board;
  timerSeconds: number;
  isSolved: boolean;
}

export interface ProgressPayload extends ProgressData {
  username: string;
  dateString: string;
  lastUpdated: string;
}

export interface LeaderboardScore {
  username: string;
  dateString: string;
  timeSeconds: number;
  timestamp: string;
}

// Helper to generate a puzzle deterministically with fallback retry seeds
function generateWithRetry(dateString: string): PuzzleData | null {
  let attempts = 0;
  let puzzle = null;
  while (!puzzle && attempts < 100) {
    const seed = attempts === 0 ? dateString : `${dateString}_retry_${attempts}`;
    puzzle = generatePuzzle(seed);
    attempts++;
  }
  if (puzzle) {
    return {
      regions: puzzle.regions,
      solution: puzzle.solution
    };
  }
  return null;
}

// Fetch the daily puzzle from Firestore or LocalStorage. If not found, autogenerates and saves it.
export async function getDailyPuzzle(dateString: string): Promise<PuzzleData | null> {
  if (USE_LOCAL) {
    const data = localStorage.getItem(`puzzle_${dateString}`);
    if (data) {
      return JSON.parse(data) as PuzzleData;
    }

    const puzzleData = generateWithRetry(dateString);
    if (puzzleData) {
      localStorage.setItem(`puzzle_${dateString}`, JSON.stringify(puzzleData));
      return puzzleData;
    }
    return null;
  }

  try {
    const docRef = doc(db, 'puzzles', dateString);
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      return docSnap.data() as PuzzleData;
    }

    // Autogenerate and save to Firestore
    const puzzleData = generateWithRetry(dateString);
    if (puzzleData) {
      try {
        await setDoc(docRef, puzzleData);
      } catch (saveError) {
        console.error("Error saving autogenerated puzzle to Firestore:", saveError);
      }
      return puzzleData;
    }
    return null;
  } catch (error) {
    console.error("Error fetching daily puzzle from Firestore:", error);
    console.log("Offline or database error. Generating offline fallback puzzle...");
    return generateWithRetry(dateString);
  }
}

// Admin: Save a puzzle to Firestore or LocalStorage
export async function savePuzzle(dateString: string, puzzleData: PuzzleData): Promise<boolean> {
  if (USE_LOCAL) {
    localStorage.setItem(`puzzle_${dateString}`, JSON.stringify(puzzleData));
    return true;
  }

  try {
    await setDoc(doc(db, 'puzzles', dateString), puzzleData);
    return true;
  } catch (error) {
    console.error("Error saving puzzle:", error);
    return false;
  }
}

// Progress saving (combines date and username for the ID)
export async function saveProgress(
  dateString: string,
  username: string,
  progressData: ProgressData
): Promise<boolean> {
  if (!username) return false;
  const id = `${dateString}_${username}`;

  const payload: ProgressPayload = {
    username,
    dateString,
    ...progressData,
    lastUpdated: new Date().toISOString()
  };

  if (USE_LOCAL) {
    localStorage.setItem(`progress_${id}`, JSON.stringify(payload));
    return true;
  }

  try {
    await setDoc(doc(db, 'progress', id), payload, { merge: true });
    return true;
  } catch (error) {
    console.error("Error saving progress:", error);
    return false;
  }
}

// Fetch user progress to resume game
export async function getProgress(dateString: string, username: string): Promise<ProgressPayload | null> {
  if (!username) return null;
  const id = `${dateString}_${username}`;

  if (USE_LOCAL) {
    const data = localStorage.getItem(`progress_${id}`);
    return data ? JSON.parse(data) : null;
  }

  try {
    const docRef = doc(db, 'progress', id);
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      return docSnap.data() as ProgressPayload;
    }
    return null;
  } catch (error) {
    console.error("Error fetching progress:", error);
    return null;
  }
}

// Leaderboard logic
export async function saveScore(dateString: string, username: string, timeSeconds: number): Promise<boolean> {
  const id = `${dateString}_${username}`;
  const payload: LeaderboardScore = {
    username,
    dateString,
    timeSeconds,
    timestamp: new Date().toISOString()
  };

  if (USE_LOCAL) {
    const existingStr = localStorage.getItem(`leaderboard_${dateString}`) || '[]';
    const existing: LeaderboardScore[] = JSON.parse(existingStr);
    const index = existing.findIndex(s => s.username === username);
    if (index >= 0) {
      if (timeSeconds < existing[index].timeSeconds) {
        existing[index] = payload;
      }
    } else {
      existing.push(payload);
    }
    localStorage.setItem(`leaderboard_${dateString}`, JSON.stringify(existing));
    return true;
  }

  try {
    await setDoc(doc(db, 'leaderboard', id), payload, { merge: true });
    return true;
  } catch (error) {
    console.error("Error saving score:", error);
    return false;
  }
}

export async function getLeaderboard(dateString: string): Promise<LeaderboardScore[]> {
  if (USE_LOCAL) {
    const existingStr = localStorage.getItem(`leaderboard_${dateString}`) || '[]';
    const existing: LeaderboardScore[] = JSON.parse(existingStr);
    // Sort ascending by time
    existing.sort((a, b) => a.timeSeconds - b.timeSeconds);
    return existing.slice(0, 10);
  }

  try {
    const q = query(
      collection(db, 'leaderboard'),
      where('dateString', '==', dateString),
      orderBy('timeSeconds', 'asc'),
      limit(10)
    );
    const querySnapshot = await getDocs(q);
    const scores: LeaderboardScore[] = [];
    querySnapshot.forEach((doc) => {
      scores.push(doc.data() as LeaderboardScore);
    });
    return scores;
  } catch (error) {
    console.error("Error fetching leaderboard:", error);
    return [];
  }
}
