/// <reference types="node" />
import { test, describe } from 'node:test';
import assert from 'node:assert';
import { generatePuzzle, hasUniqueSolution } from './puzzleGenerator';
import { MAX_BOARD_SIZE } from './gameLogic';

describe('Queens Puzzle Generator and Solver Native Unit Tests', () => {
    test('hasUniqueSolution: should return false for a board with multiple solutions', () => {
        const regionsMultiple = [
            [0, 0, 0, 0, 0],
            [1, 1, 1, 1, 1],
            [2, 2, 2, 2, 2],
            [3, 3, 3, 3, 3],
            [4, 4, 4, 4, 4],
        ];

        const result = hasUniqueSolution(regionsMultiple);
        assert.strictEqual(result, false);
    });

    test('hasUniqueSolution: should return false for an unsolvable board', () => {
        const regionsUnsolvable = [
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0],
        ];

        const result = hasUniqueSolution(regionsUnsolvable);
        assert.strictEqual(result, false);
    });

    test('hasUniqueSolution: should return true for a valid unique puzzle generated by generatePuzzle', () => {
        const puzzle = generatePuzzle('seed_for_unique_test');
        assert.ok(puzzle);
        if (puzzle) {
            const result = hasUniqueSolution(puzzle.regions);
            assert.strictEqual(result, true);
        }
    });

    test('generatePuzzle: should generate a valid, unique-solution puzzle matching the board size and rules', () => {
        const puzzle = generatePuzzle('game_rules_test_seed');
        assert.ok(puzzle);
        if (puzzle) {
            const { regions, solution } = puzzle;

            // 1. Correct board size
            assert.strictEqual(regions.length, MAX_BOARD_SIZE);
            regions.forEach((row) => {
                assert.strictEqual(row.length, MAX_BOARD_SIZE);
            });

            // 2. Correct number of queens in solution
            assert.strictEqual(solution.length, MAX_BOARD_SIZE);

            // 3. Solution constraints verification
            const rows = new Set<number>();
            const cols = new Set<number>();
            const regionIds = new Set<number>();

            solution.forEach((queen) => {
                rows.add(queen.rowIndex);
                cols.add(queen.columnIndex);
                regionIds.add(regions[queen.rowIndex][queen.columnIndex]);
            });

            // Exactly one queen per row, column, and region
            assert.strictEqual(rows.size, MAX_BOARD_SIZE);
            assert.strictEqual(cols.size, MAX_BOARD_SIZE);
            assert.strictEqual(regionIds.size, MAX_BOARD_SIZE);

            // No two queens touch (adjacent orthogonally or diagonally)
            for (let i = 0; i < solution.length; i++) {
                for (let j = i + 1; j < solution.length; j++) {
                    const q1 = solution[i];
                    const q2 = solution[j];
                    const rowDiff = Math.abs(q1.rowIndex - q2.rowIndex);
                    const colDiff = Math.abs(q1.columnIndex - q2.columnIndex);
                    assert.ok(rowDiff > 1 || colDiff > 1);
                }
            }

            // 4. Double check uniqueness
            assert.strictEqual(hasUniqueSolution(regions), true);
        }
    });

    test('generatePuzzle: should be deterministic when using the same seed', () => {
        const puzzle1 = generatePuzzle('determ_seed');
        const puzzle2 = generatePuzzle('determ_seed');

        assert.ok(puzzle1);
        assert.ok(puzzle2);
        assert.deepStrictEqual(puzzle1, puzzle2);
    });

    test('generatePuzzle: should generate different puzzles for different seeds', () => {
        const puzzle1 = generatePuzzle('seed_a');
        const puzzle2 = generatePuzzle('seed_b');

        assert.ok(puzzle1);
        assert.ok(puzzle2);
        assert.notDeepStrictEqual(puzzle1, puzzle2);
    });
});
